//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuIDE - Quantum Integrated Development Environment
        ///Version: 1.0.0
        ///© 2014 Joanna Patrzyk, Bartłomiej Patrzyk.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Control Bit.
        /// </summary>
        public static string AddControl {
            get {
                return ResourceManager.GetString("AddControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Parameter.
        /// </summary>
        public static string AddParam {
            get {
                return ResourceManager.GetString("AddParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Qubit to Register.
        /// </summary>
        public static string AddQubit {
            get {
                return ResourceManager.GetString("AddQubit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Register.
        /// </summary>
        public static string AddRegister {
            get {
                return ResourceManager.GetString("AddRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Step.
        /// </summary>
        public static string AddStep {
            get {
                return ResourceManager.GetString("AddStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        public static string Amplitude {
            get {
                return ResourceManager.GetString("Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If amplitudes are not normalized (probabilities of possible states do not sum up to 1), they will be automatically normalized before register creation..
        /// </summary>
        public static string AmplitudesNormalizationCaution {
            get {
                return ResourceManager.GetString("AmplitudesNormalizationCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Value :.
        /// </summary>
        public static string AngleValue {
            get {
                return ResourceManager.GetString("AngleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:
        ///Joanna Patrzyk (jpatrzyk@quide.eu)
        ///Bartłomiej Patrzyk (bpatrzyk@quide.eu).
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit Designer.
        /// </summary>
        public static string CircuitDesigner {
            get {
                return ResourceManager.GetString("CircuitDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Circuit.
        /// </summary>
        public static string ClearCircuit {
            get {
                return ResourceManager.GetString("ClearCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection [Delete].
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite Gate.
        /// </summary>
        public static string Composite {
            get {
                return ResourceManager.GetString("Composite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Output.
        /// </summary>
        public static string ConsoleOutput {
            get {
                return ResourceManager.GetString("ConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy [Ctrl+C].
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Result.
        /// </summary>
        public static string CopyResult {
            get {
                return ResourceManager.GetString("CopyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Phase Kick (Phase Shift) Gate For QFT.
        /// </summary>
        public static string CPhaseShift {
            get {
                return ResourceManager.GetString("CPhaseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut [Ctrl+X].
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Column.
        /// </summary>
        public static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Qubit.
        /// </summary>
        public static string DeleteQubit {
            get {
                return ResourceManager.GetString("DeleteQubit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Register.
        /// </summary>
        public static string DeleteRegister {
            get {
                return ResourceManager.GetString("DeleteRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Distance Value (k) :.
        /// </summary>
        public static string DistValue {
            get {
                return ResourceManager.GetString("DistValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop selected gates.
        /// </summary>
        public static string DragGates {
            get {
                return ResourceManager.GetString("DragGates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name for the new Composite Gate :.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Gate.
        /// </summary>
        public static string EraseGate {
            get {
                return ResourceManager.GetString("EraseGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Bit.
        /// </summary>
        public static string FlipBit {
            get {
                return ResourceManager.GetString("FlipBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code From Circuit.
        /// </summary>
        public static string GenerateCode {
            get {
                return ResourceManager.GetString("GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Circuit From Code.
        /// </summary>
        public static string GenerateFromCode {
            get {
                return ResourceManager.GetString("GenerateFromCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to take away your free [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GPLText {
            get {
                return ResourceManager.GetString("GPLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Composite Gate from selected gates.
        /// </summary>
        public static string GroupTip {
            get {
                return ResourceManager.GetString("GroupTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hadamard Gate.
        /// </summary>
        public static string Hadamard {
            get {
                return ResourceManager.GetString("Hadamard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run In Console.
        /// </summary>
        public static string InConsole {
            get {
                return ResourceManager.GetString("InConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial register state:.
        /// </summary>
        public static string InitState {
            get {
                return ResourceManager.GetString("InitState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial register value.
        /// </summary>
        public static string InitValue {
            get {
                return ResourceManager.GetString("InitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Column on the Left.
        /// </summary>
        public static string InsertColumnLeft {
            get {
                return ResourceManager.GetString("InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Column on the Right.
        /// </summary>
        public static string InsertColumnRight {
            get {
                return ResourceManager.GetString("InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Qubit Above.
        /// </summary>
        public static string InsertQubitAbove {
            get {
                return ResourceManager.GetString("InsertQubitAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Qubit Below.
        /// </summary>
        public static string InsertQubitBelow {
            get {
                return ResourceManager.GetString("InsertQubitBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Register Above.
        /// </summary>
        public static string InsertRegisterAbove {
            get {
                return ResourceManager.GetString("InsertRegisterAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Register Below.
        /// </summary>
        public static string InsertRegisterBelow {
            get {
                return ResourceManager.GetString("InsertRegisterBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row Above.
        /// </summary>
        public static string InsertRowAbove {
            get {
                return ResourceManager.GetString("InsertRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row Below.
        /// </summary>
        public static string InsertRowBelow {
            get {
                return ResourceManager.GetString("InsertRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inversed Conditional Phase Kick (Phase Shift) Gate For QFT.
        /// </summary>
        public static string InvCPhaseShift {
            get {
                return ResourceManager.GetString("InvCPhaseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuIDE is available under the GNU General Public License:.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matrix is not unitary..
        /// </summary>
        public static string MatrixNotUnitary {
            get {
                return ResourceManager.GetString("MatrixNotUnitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New [Ctrl+N].
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Forward [F7].
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open [Ctrl+O].
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Matrix :.
        /// </summary>
        public static string OperationMatrix {
            get {
                return ResourceManager.GetString("OperationMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste [Ctrl+V].
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Kick (Phase Shift) Gate.
        /// </summary>
        public static string PhaseKick {
            get {
                return ResourceManager.GetString("PhaseKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Scale Gate.
        /// </summary>
        public static string PhaseScale {
            get {
                return ResourceManager.GetString("PhaseScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π.
        /// </summary>
        public static string Pi {
            get {
                return ResourceManager.GetString("Pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π / 2.
        /// </summary>
        public static string Pi_2 {
            get {
                return ResourceManager.GetString("Pi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π / 3.
        /// </summary>
        public static string Pi_3 {
            get {
                return ResourceManager.GetString("Pi_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π / 4.
        /// </summary>
        public static string Pi_4 {
            get {
                return ResourceManager.GetString("Pi_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π / 6.
        /// </summary>
        public static string Pi_6 {
            get {
                return ResourceManager.GetString("Pi_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π / 8.
        /// </summary>
        public static string Pi_8 {
            get {
                return ResourceManager.GetString("Pi_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        public static string Pointer {
            get {
                return ResourceManager.GetString("Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Back [F6].
        /// </summary>
        public static string PrevStep {
            get {
                return ResourceManager.GetString("PrevStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability.
        /// </summary>
        public static string Probability {
            get {
                return ResourceManager.GetString("Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability Scale.
        /// </summary>
        public static string ProbabilityScale {
            get {
                return ResourceManager.GetString("ProbabilityScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantum Fourier Transform.
        /// </summary>
        public static string QFT {
            get {
                return ResourceManager.GetString("QFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qubits.
        /// </summary>
        public static string Qubits {
            get {
                return ResourceManager.GetString("Qubits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of new qubits.
        /// </summary>
        public static string QubitsNumber {
            get {
                return ResourceManager.GetString("QubitsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Qubit from Register.
        /// </summary>
        public static string RemoveQubit {
            get {
                return ResourceManager.GetString("RemoveQubit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart [F5].
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate X Gate.
        /// </summary>
        public static string RotateX {
            get {
                return ResourceManager.GetString("RotateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Y Gate.
        /// </summary>
        public static string RotateY {
            get {
                return ResourceManager.GetString("RotateY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Z Gate.
        /// </summary>
        public static string RotateZ {
            get {
                return ResourceManager.GetString("RotateZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run To End [F8].
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run In Console.
        /// </summary>
        public static string RunInConsole {
            get {
                return ResourceManager.GetString("RunInConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save [Ctrl+S].
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As... [Ctrl+Alt+S].
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Composite Gate....
        /// </summary>
        public static string SelectCompositeGate {
            get {
                return ResourceManager.GetString("SelectCompositeGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Composite Gate :.
        /// </summary>
        public static string SelectedCompositeGate {
            get {
                return ResourceManager.GetString("SelectedCompositeGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection [Shift] (to move selected, press Shift+Ctrl).
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Method :.
        /// </summary>
        public static string SelectMethod {
            get {
                return ResourceManager.GetString("SelectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About QuIDE....
        /// </summary>
        public static string ShowAbout {
            get {
                return ResourceManager.GetString("ShowAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Calculator [Ctrl+K].
        /// </summary>
        public static string ShowCalculator {
            get {
                return ResourceManager.GetString("ShowCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Non-Zero.
        /// </summary>
        public static string ShowOnlyNonZero {
            get {
                return ResourceManager.GetString("ShowOnlyNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma X Gate (Not).
        /// </summary>
        public static string SigmaX {
            get {
                return ResourceManager.GetString("SigmaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma Y Gate.
        /// </summary>
        public static string SigmaY {
            get {
                return ResourceManager.GetString("SigmaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma Z Gate.
        /// </summary>
        public static string SigmaZ {
            get {
                return ResourceManager.GetString("SigmaZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Root of Not Gate.
        /// </summary>
        public static string SqrtX {
            get {
                return ResourceManager.GetString("SqrtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude of the state. It is a complex number, which squared magnitude gives the probability of the state..
        /// </summary>
        public static string StateAmplitude {
            get {
                return ResourceManager.GetString("StateAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of the state. The bar&apos;s length represents probability value. Color represents the phase of state&apos;s amplitude (which is complex number)..
        /// </summary>
        public static string StateProbability {
            get {
                return ResourceManager.GetString("StateProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State binary representation.
        /// </summary>
        public static string StateQubits {
            get {
                return ResourceManager.GetString("StateQubits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Visibility.
        /// </summary>
        public static string StatesVisibility {
            get {
                return ResourceManager.GetString("StatesVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal value of the state.
        /// </summary>
        public static string StateValue {
            get {
                return ResourceManager.GetString("StateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Circuit.
        /// </summary>
        public static string ToCircuit {
            get {
                return ResourceManager.GetString("ToCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Code.
        /// </summary>
        public static string ToCode {
            get {
                return ResourceManager.GetString("ToCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string Ungroup {
            get {
                return ResourceManager.GetString("Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup Composite Gate.
        /// </summary>
        public static string UngroupTip {
            get {
                return ResourceManager.GetString("UngroupTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Unitary Gate.
        /// </summary>
        public static string Unitary {
            get {
                return ResourceManager.GetString("Unitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
